![image.png](attachment:image.png)

### Fala devs, blz?

Temos a honra de apresentar nossa 4ᵃ (quarta) lista de exercícios do Curso de Python 2023 ! 🥳

Dessa vez o tema será o módulo 2, que retrata sobre importações de bibliotecas e sobre a biblioteca _Numpy_ - muito importante para realização de códigos matemáticos e melhora de desempenho das operações.

Esperamos que seja um estudo produtivo e que se divirtam aprendendo!

---
### INSTRUÇÕES:

A realização da lista deve ser feita através do Jupyter Notebook.

Não é obrigatório enviar a lista para fins de certificação na plataforma. No entanto, para os alunos da USP interessados em participar do processo seletivo ou obter créditos AAC (apenas FEANOS), é necessário enviar TODAS as listas.

É altamente recomendado enviar as listas ou, pelo menos, executá-las para praticar todo o conhecimento adquirido durante o curso.

Este DESAFIO foi elaborado para desafiá-lo de verdade. Por isso, não desista de tentar e de continuar com o curso. Ao longo das listas, você perceberá que terá cada vez mais ferramentas para completá-las.

Se surgirem dúvidas sobre a lista, participe das monitorias que serão realizadas às quintas e sábados, das 17h às 18h, no DISCORD. Se o problema não for resolvido, envie uma mensagem para contato.feadev@gmail.com.

O gabarito será disponibilizado na plataforma após o término do período de envio.

---

In [3]:
# Vamos começar importando algumas bibliotecas importantes para os exercícios. ps: Escolham o método que desejarem para resolução.
import math
import numpy as np
import random as rd
import datetime

---
## Questão 0


<h3> Dr. Python </h3>


![gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnZjMmd5ZzRiOHVka3VkZmlwZXBkNm1lNndyMjU2NzB6ZWxkajV4ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/9J7tdYltWyXIY/giphy.gif)

Você foi contratado por uma investidora misteriosa - notavelmente muito rica e influente - para resolver um problema com a internet. Ele está tendo problemas de acesso e percebe que isso é causado por um vírus codificado por uma charada. Sabendo que a única forma de resolver seria acionar um especialista, ela decide te pagar muito dinheiro e a possibilidade de ser contratado por uma grande empresa caso consiga resolver o enigma do vírus.


Segue o texto originado pelo vírus:

#### _"Dois números um, onde há 3 torna-se 5, coloque dois zeros ao fundo, trate de juntar tudo e retorno seu acesso ao WebMundo!"_


<br>

Juntamente ao texto, o vírus fornece o espaço a seguir com alguns algoritmos e arrays para auxiliar na resolução do caso:

In [11]:
# Algoritmo viral
lista_um = list(np.ones(2))
lista_dois = [3,3]
lista_tres = list(np.zeros(2))

print(lista_um, lista_dois, lista_tres)

[1.0, 1.0] [3, 3] [0.0, 0.0]



Tendo ciência da informação acima descrita, crie um código que _concatene as listas em um array_, lembrando de _alterar os valores_ necessários para _satisfazer a condição_ do vírus ("onde há 3 torna-se 5...")
<br>

In [20]:
# Seu código começa aqui

# uma opção viável é simplesmente trocar 3 por 5 via indexação. é o que este código está fazendo. 
lista_dois[0] = 5
lista_dois[1] = 5

# depois, podemos somar as listas em uma só, e utilizar np.array para transformar em um array
lista_concatenada = lista_um + lista_dois + lista_tres
array_final = np.array(lista_concatenada)
array_final

#outra opção para trocar 3 por 5 seria utilizando list compreheensions. o código está na próxima célula.

array([1., 1., 5., 5., 0., 0.])

In [19]:
lista_dois = [5 if x == 3 else x for x in lista_dois] # utiliza de condicionais para achar os valores '3', e os troca por '5'.

lista_concatenada = lista_um + lista_dois + lista_tres
array_final2 = np.array(lista_concatenada) # termina da mesma maneira.
array_final2

# a vantagem deste método é não ter que fazer cada um manualmente e não precisar saber o índice de cada valor '3'.

array([1., 1., 5., 5., 0., 0.])

---
## Questão 1

### Cien Tenpo

![gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZTZqd3YxNTgyemQyNXE5ODBtYmM5ZTVhbXEwYXZvbzg2YjJoODh4aCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/QBd2kLB5qDmysEXre9/giphy.gif)

Seu amigo acaba de chegar de outro país e se encontra muito confuso com o fuso horário novo e todas as nomenclaturaas. Sabendo do seus conhecimentos em programação, ele decide pedir ajuda para saber a hora com um simples executar de código.

<br>

Pensando nisso, crie um script utilizando a biblioteca _datetime_ que retorne a data atual junto a hora. Armazene em uma variável e exiba com uma mensagem amigável para seu amigo como o exemplo a seguir:

"Olá Cien Tenpo, segue a data e horário em nosso fuso: DATA"

---

###### ps: Caso tenha alguma dúvida com essa biblioteca, pode consultar aqui um exemplo de como usar:

https://www.w3schools.com/python/python_datetime.asp

In [27]:
# Seu código começa aqui
from datetime import datetime

data_hora_atual = datetime.now() # pega a data e hora atual
data_formatada = data_hora_atual.strftime("%Y-%m-%d %H:%M:%S") # definindo como deve ser formatada a data

#print final
print(f"Olá Cien Tenpo, segue a data e horário em nosso fuso: {data_formatada}")

Olá Cien Tenpo, segue a data e horário em nosso fuso: 2024-06-12 19:51:02


---
## Questão 2

### Sorteando o sorteio

Em um passeio qualquer pela sua cidade, você descobre uma oportunidade incrível de visitar um bingo famoso da cidade em que aquele que sorteia as bolinhas ganha o seu doce preferido como salário. Não querendo perder essa chance, você decide dar uma chance para a vaga e acaba sendo encarregado pela função. Nesse sentido, te passam instruções essenciais para você receber sua recompensa:
- Você deve sortear e exibir cada número no telão
- Após exibir, você deve organizar em ordem crescente os valores no telão
- Ao final, a caixa precisa estar disposta com os valores indo de 1 até 20 em ordem crescente

Segue um código abaixo com os valores a serem sorteados:

In [45]:
# Bolinhas a serem sorteadas

numeros_caixa = list(range(1,21,1))
# numero_aleatorio = rd.choice(numeros_caixa)

Sabendo disso, faça um script que _rode todos os números na caixa e sorteie valor a valor_, _exibindo-os no telão_ (printando) e logo em seguida já _organizando em ordem crescente(sort)_:

In [66]:
# Seu código começa aqui

numeros_caixa = list(range(1, 21))

sorteados = [] # inicializa uma lista vazia, à qual vamos inserir os números sorteados.
for _ in range(len(numeros_caixa)): # utiliza de um loop for para, para cada elemento de 1 a 20, sortear um, adicioná-lo à lista zerada e removê-lo da lista numeros_caixa, sequencialmente.
    
    numero_aleatorio = rd.choice(numeros_caixa)
    
    sorteados.append(numero_aleatorio) 
    numeros_caixa.remove(numero_aleatorio)
    
    print(f"Sorteado: {numero_aleatorio}") # vai printando cada número
    
    sorteados.sort() # organizamos em ordem crescente e printamos o resultado final.
    print("Números organizados em ordem crescente:", sorteados)

# obs: interpretei que o que o exercício queria era printar diversas vezes a ordem crescente a cada sorteio, e não apenas uma vez no final.
# senti que faz mais sentido, considerando que na outra opção seria sempre a mesma lista de 1 a 20 em ordem crescente (última linha do meu output)

Sorteado: 2
Números organizados em ordem crescente: [2]
Sorteado: 16
Números organizados em ordem crescente: [2, 16]
Sorteado: 7
Números organizados em ordem crescente: [2, 7, 16]
Sorteado: 6
Números organizados em ordem crescente: [2, 6, 7, 16]
Sorteado: 13
Números organizados em ordem crescente: [2, 6, 7, 13, 16]
Sorteado: 3
Números organizados em ordem crescente: [2, 3, 6, 7, 13, 16]
Sorteado: 18
Números organizados em ordem crescente: [2, 3, 6, 7, 13, 16, 18]
Sorteado: 20
Números organizados em ordem crescente: [2, 3, 6, 7, 13, 16, 18, 20]
Sorteado: 14
Números organizados em ordem crescente: [2, 3, 6, 7, 13, 14, 16, 18, 20]
Sorteado: 5
Números organizados em ordem crescente: [2, 3, 5, 6, 7, 13, 14, 16, 18, 20]
Sorteado: 11
Números organizados em ordem crescente: [2, 3, 5, 6, 7, 11, 13, 14, 16, 18, 20]
Sorteado: 19
Números organizados em ordem crescente: [2, 3, 5, 6, 7, 11, 13, 14, 16, 18, 19, 20]
Sorteado: 9
Números organizados em ordem crescente: [2, 3, 5, 6, 7, 9, 11, 13, 14, 16,

---
## Questão 3

### Realizando alguns cálculos
![GIF](https://media.giphy.com/media/21I1WOUDnct4EmSNa6/giphy.gif)

Cansado de viver uma vida de bicos em bingos e resolvendo problemas de pessoas ricas, você opta pela vida estável como contador. Logo que começa em seu emprego seu chefe já te passa uma simples demanda: Somar os arranjos de valores que sejam compatíveis!

<br>

Você como bom dever não vê dificuldade e já parte para resolver o código de imediato utilizando a biblioteca numpy em Python, se deparando com os seguintes arrays transcritos:

In [68]:
# Arranjos
Arranjo_1 = np.array([[1, 2, 3],
                      [4, 5, 6]])

Arranjo_2 = np.array([[13, 14],
                      [15, 16],
                      [17, 18]])

Arranjo_3 = np.array([[7, 8, 9],
                      [10, 11, 12]])

Agora, selecione os arrays que são compatíveis e crie um código simples que realize a soma desses arrays.

In [74]:
# Seu código começa aqui

# os arrays compatíveis para soma são 1 e 3. 

soma = Arranjo_1 + Arranjo_3

soma

array([[ 8, 10, 12],
       [14, 16, 18]])

In [106]:
# se quisermos podemos transpor o arranjo soma para possibilitar a soma dele ao arranjo 2:

soma_tranposto = soma.T
soma2 = soma_tranposto + Arranjo_2
soma2

array([[21, 28],
       [25, 32],
       [29, 36]])

## Questão 4
### Mediano
Seu chefe, notando o sucesso no demanda anterior, te passa já uma nova tarefa: Calcular a diferença entre a média dos três arranjos.

---
Seguindo a lógica, use os valores da questão anterior para criar um código que realize o cálculo da diferença entre as médias.

In [115]:
# Seu código começa aqui

# utilizando np.mean() para obter a média dos valores de cada arranjo: 

media1 = np.mean(Arranjo_1)
media2 = np.mean(Arranjo_2)
media3 = np.mean(Arranjo_3)

diferenca = media1 - media2 - media3 # obs: assumi media1 - media2 - media3, mas poderíamos fazer, por exemplo, media3 - media2 - media1. 
diferenca

# ou ainda poderiamos calcular de 2 em 2 a diferença entre as médias, como na próxima célula:

-21.5

In [129]:
diferenca1_2 = media1 - media2
diferenca1_3 = media1 - media3
diferenca2_3 = media2 - media3

print(diferenca1_2, diferenca1_3, diferenca2_3)

-12.0 -6.0 6.0


---
## DESAFIO

### Filtrando (um café matemágico ?)

![gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3RrbG9uMG53azM4MHhxemtrNzdvbTYxNTA1NzhwaHozeDFnZmI3OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/OV2uRXy5VIBoPAsH9A/giphy.gif)

Poderia ser um desafio interessante tomar um café matemático?

<br>

A proposta desse desafio é justamente testar essa hipótese !

Temos uma sequência de arranjos que correspondem a "camadas" do café e precisamos ir afunilando e remodelando para que possamos ir somando até formar um único valor (que corresponde ao nosso "café filtrado").

##### PS: alguns grãos estão acima do valor máximo que a cafeteira suporte. Substitua grãos maiores que 50 (gramas) pelo valor 30

In [127]:
# Camadas de grãos de café para serem filtrados. Para fins didáticos imagine que são grãos inteiros e isso não afeta o processo
# Camadas de grãos de café para serem filtrados. Para fins didáticos imagine que são grãos inteiros e isso não afeta o processo
camada_1 = np.array([[5, 2, 7],
                     [12, 5, 9]])

camada_2 = np.array([[15, 8],
                     [4, 10],
                     [52, 65]])

camada_3 = np.array([[17, 11, 19],
                     [6, 22, 26]])

camada_4 = np.array([[78, 15],
                     [16, 23],
                     [12, 32]])

Tendo essas camadas em vista, crie um código que remodele (reshape/resize) os arranjos para uma dimensão comum e possibilite a soma. Ao final printe a soma de todos os valores.

_Lembre-se de corrigir grãos maiores que 50 para um valor 30 (seria uma margem de erro para a máquina)_

In [128]:
# Seu código começa aqui

camada_2 = camada_2.reshape(2, 3) # podemos manter as camadas 1 e 3, e reshape as camadas 2 e 4 para o formato comum.
camada_4 = camada_4.reshape(2, 3)

# utilizando uma indexação booleana para eliminar os elementos maiores que 50 em todas as camadas (embora nem todas tenham valores maiores que 50)
camada_1[camada_1 > 50] = 30
camada_2[camada_2 > 50] = 30
camada_3[camada_3 > 50] = 30
camada_4[camada_4 > 50] = 30

# somando tudo, utilizando np.sum():
soma_total = np.sum(camada_1 + camada_2 + camada_3 + camada_4)

print('Total dos valores:', soma_total)

Total dos valores: 366
